# Generated by Django 3.2.4 on 2021-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
